### ISSUE TITLE
[documentation] enhance documentation

### ISSUE THREAD

**Issue by florianlenz** [MetaMask/web3-provider-engine#194]
Hi,

i would like to use the provider engine in one of my project. I got it working but i have absolutely no idea why i need all Providers. 

Questions: 
* [ ] What is a filter provider?
* [ ] What is a pending nonce provider and what does it do?
* [ ] What providers are required for an engine?
* [ ] For what is [this](https://github.com/MetaMask/provider-engine/blob/master/zero.js) used? Is it like a minimal config?
* [ ] What engine event's are available (at least, 'error' and 'block' as seen in the example code)? 

I can write down the answers into a FAQ or smth like that. I "just" need the answers. 

Thank you.

**Comment by danfinlay** [comment]
1. Filter provider polyfills the `filter` API for use with stateless RPC providers like Infura. The Filter API involves creating a selector for a type of Event/Logs on the blockchain, and listening for them as they happen. Since this requires stateful registration, an RPC provider can't always support it, and so this provider can be used to provide the same API with polling client side.
2. Pending nonce tracker is used for retrieving an account's current nonce. The nonce is related to how ethereum accounts assemble transactions. Each valid transaction has a nonce that is 1 higher than the previous nonce. Normal RPCs will only report how the `transactionCount` of completed transactions, but for sending many transactions at once, the pending nonce tracker will return a number that *should be* incremented appropriately, accounting for successfully transmitted transactions.
3. An engine can be assembled with as little as a single "out" provider, like the `fetch` or `rpc` subprovider, which simply passes methods through to its data provider. Most other subproviders are "middleware", and either affect requests or provide additional APIs.
4. The `zero` provider is a drop-in provider-engine instance, as used in `MetaMask`. It has a comprehensive combination of caching, nonce tracking, and account management, and is suitable for composing a local account manager and provider.
5. Don't be afraid of reading the source code! It's fairly simple! You can see [here](https://github.com/MetaMask/provider-engine/blob/master/index.js#L34) that emitted events are `block`, `sync`, and `latest`.
