### ISSUE TITLE
Nonce values stuck too low when using Nonce Tracker

### ISSUE THREAD

**Issue by dekz** [MetaMask/web3-provider-engine#213]
We've noticed that sometimes a `getTransactionCount` hitting an INFURA node can return a value that is invalid when used as a nonce in a transaction. 

```
{"code":-32010,"message":"Transaction nonce is too low. Try incrementing the nonce."}
```

When the Provider Engine Nonce tracker is used, one can end up in a loop of invalid nonces as the value from `getTransactionCount` is now cached. The nonce is [never cleared](https://github.com/MetaMask/provider-engine/blob/master/subproviders/nonce-tracker.js#L56) from an error during `sendTransaction`, even if the nonce is the reason the `sendTransaction` failed.

**Comment by danfinlay** [comment]
Have you captured one of these infura responses that returns an invalid nonce value? Have any reproduction steps?

**Comment by dekz** [comment]
It's a difficult one to reproduce live. My hunch is a INFURA node that is not yet fully synced or became out of sync. The response itself is not an invalid response, it is just not the correct total transaction account when submitting a transaction. 

I believe this could also occur if `getTransactionCount` was used out of lock-step with `sendTransaction` from an account shared in separate instances.

**Comment by danfinlay** [comment]
That latter theory would make sense. We basically can’t support having the same account being used by different computers at once, without adding some central orchestration service.

Even if infura is behind, MetaMask is able to recognize if it has local confirmed or pending transactions, and will set its nonce correctly.

Afaik, running multiple instances of metamask is the only current way to get this result.

**Comment by dekz** [comment]
What do you think about clearing the cached value for that account on error? Or do you think that would have other consequences?

**Comment by Schaeff** [comment]
I think I have the same issue:
On Kovan (no problem on testrpc), sending a lot of transactions back to back from the same account sometimes results in Parity refusing transactions due to the nonce being too low. I'm confident there's no other instance of the subprovider using the same account at the same time.

**Comment by danfinlay** [comment]
> What do you think about clearing the cached value for that account on error?

That wouldn't do anything. The problem isn't that we have a badly cached value, it's that one metamask isn't aware of what the other one is doing. We could try doing weird things, like incrementing some local cache blindly, but that sounds really dangerous and bug-prone in its own way.

> I think I have the same issue:
On Kovan (no problem on testrpc), sending a lot of transactions back to back from the same account sometimes results in Parity refusing transactions due to the nonce being too low. I'm confident there's no other instance of the subprovider using the same account at the same time.

If no other instance is using the same account at the same time, you're definitely describing a different issue, feel free to open a new issue about it.

**Comment by dekz** [comment]
I think I communicated this issue poorly. We are using Provider Engine in our Kovan Faucet (this issue is not from a generic Metamask usage in browsers). We are not using the account from multiple places, this was just a general step to reproduce.

We do believe the issue is caused from using INFURA and the backend gets a response from a node which is out of sync (or still syncing). If I find the time I will attempt to run a script to reproduce this and display that its possible to hit an INFURA node (or any node really) which can become out of sync. 

It seems unlikely but it does tend to pop up for us occasionally.

**Comment by roderik** [comment]
I believe this might be a specific issue with Parity PoA and/or short blocktime setups and not Infura. We are running into the same issues on a permissioned setup that looks a lot like Kovan.

**Comment by kumavis** [comment]
we no longer use this nonce-tracker in metamask. we have some larger machinery now that is more intelligent that we'd like to break out + publish, then bring into provider-engine

**Comment by danfinlay** [comment]
I'm not sure our new nonce logic could live in provider-engine by itself: It depends on having a list of sent/pending transactions, so it can increment over the highest nonce between that and the network's latest confirmed tx for that account.

I think nonce tracking with provider-engine is probably going to continue to be inadequate for as long as it doesn't also track sent/pending transactions.
